In [1]:
import pandas as pd
import numpy as np
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
"""see scikit-learn.org/stable/modules/feature_extraction.html and 
scikit-learn.org/stable/modules/classes.html#text-feature-extraction-ref 
for TfidfVectorizer parameters"""

data = pd.read_csv('job_skill_short.csv', dtype = str)
corpus_null = data['Responsibilities']
corpus = corpus_null.fillna(" ") # clean 15 empty lines, replace null entries with space

#replacing punctuation
corpus = corpus.str.replace('\'','')
corpus = corpus.str.replace("-",' ')
corpus = corpus.str.replace(",",'')
corpus = corpus.str.replace("\\n",'. ')
corpus = corpus.str.replace('[^\w\s]','.')
corpus = corpus.str.replace("\..",'.')
#corpus = corpus.str.replace('.','')

st = PorterStemmer()
corpus = corpus.apply(lambda x: " ".join([st.stem(word) for word in x.split()]))#stem words

# tokenize all words 3 letters or longer.  Ignore 3-grams that occur in more than 727 or in less than 3 descriptions
vectorizer = CountVectorizer(stop_words = 'english', strip_accents=ascii, ngram_range=(1, 3), analyzer = 'word',max_df=0.6, min_df=.0025)
bow = np.array(vectorizer.fit_transform(corpus).toarray())
print("extracted " + str(len(vectorizer.get_feature_names())) + " features from " + str(len(corpus)) + " documents\n")
print(vectorizer.get_feature_names())




extracted 9571 features from 1227 documents

['24x7', '30', '30 time', '30 time region', '50', '50 time', 'abil', 'abil manag', 'abil manag risk', 'abl', 'abl support', 'abl support busi', 'abus', 'acceler', 'acceler agreement', 'acceler agreement closur', 'access', 'accomplish', 'accord', 'account', 'account ensur', 'account ensur busi', 'account erritori', 'account erritori strategi', 'account implic', 'account manag', 'account market', 'account performance', 'account plan', 'account plan custom', 'account plan support', 'account strategi', 'account strategi gener', 'account team', 'account team develop', 'accounts', 'accounts build', 'accounts build implement', 'accounts connect', 'accounts connect key', 'accur', 'accur achiev', 'accur achiev strateg', 'accur commun', 'accur commun product', 'accur forecast', 'accur forecast achiev', 'accur project', 'accur project inform', 'accur reflect', 'accur reflect visual', 'accur time', 'accuraci', 'accuraci financi', 'accuracy', 'achiev', '

In [16]:
print(bow)

print(type(bow))
print(bow.shape)
print(len(vectorizer.get_feature_names()))

dtm = pd.DataFrame(bow, columns=vectorizer.get_feature_names())
new_data = pd.concat([data, dtm], axis=1)
print(new_data)
new_data.to_csv("dtm_jobs.csv", header= True)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
(1227, 9571)
9571
     Unnamed: 0 Company                                              Title  \
0             1  Google                       Google Cloud Program Manager   
1             2  Google  Supplier Development Engineer (SDE), Cable/Con...   
2             3  Google  Data Analyst, Product and Tools Operations, Go...   
3             4  Google            Developer Advocate, Partner Engineering   
4             5  Google     Program Manager, Audio Visual (AV) Deployments   
5             6  Google  Associate Account Strategist (Czech/Slovak), G...   
6             7  Google  Supplier Development Engineer, Camera, Consume...   
7             8  Google  Strategic Technology Partner Manager, Healthca...   
8             9  Google    Manufacturing Business Manager, Google Hardware   
9            10  Google  Solutions Architect, Healthcare a