In [34]:
import pandas as pd
import numpy as np
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

In [37]:
"""see scikit-learn.org/stable/modules/feature_extraction.html and 
scikit-learn.org/stable/modules/classes.html#text-feature-extraction-ref 
for TfidfVectorizer parameters"""

data = pd.read_csv('job_skill_short.csv', dtype = str)
corpus_null = data['Responsibilities']
corpus = corpus_null.fillna(" ") # clean 15 empty lines, replace null entries with space

#replacing punctuation
corpus = corpus.str.replace('\'',' ')
corpus = corpus.str.replace("-",' ')
corpus = corpus.str.replace(",",'')
corpus = corpus.str.replace("\\n",'. ')
corpus = corpus.str.replace('[^\w\s]','.')
corpus = corpus.str.replace("\..",'.')
#corpus = corpus.str.replace('.','')

st = PorterStemmer()
corpus = corpus.apply(lambda x: " ".join([st.stem(word) for word in x.split()]))#stem words

# tokenize all words 3 letters or longer.  Ignore 3-grams that occur in more than 727 or in less than 12 descriptions
vectorizer = CountVectorizer(stop_words = 'english', strip_accents=ascii, ngram_range=(1, 3), analyzer = 'word',max_df=0.6, min_df=.01)
bow = np.array(vectorizer.fit_transform(corpus).toarray())
print("extracted " + str(len(vectorizer.get_feature_names())) + " features from " + str(len(corpus)) + " documents\n")
print(vectorizer.get_feature_names())




extracted 1804 features from 1227 documents

['abl', 'acceler', 'access', 'account', 'account manag', 'account plan', 'account strategi', 'account strategi gener', 'account team', 'accounts', 'accur', 'accur achiev', 'accur achiev strateg', 'achiev', 'achiev strateg', 'achiev strateg goal', 'achiev strateg goals', 'acquisit', 'act', 'act liaison', 'act trust', 'act trust advisor', 'action', 'activ', 'activ includ', 'activ technolog', 'activ technolog advocaci', 'activities', 'activities prepar', 'activities prepar deliv', 'ad', 'ad hoc', 'address', 'adopt', 'adopt relat', 'adopt relat activities', 'advanc', 'advertis', 'advertisers', 'advic', 'advic custom', 'advic custom optim', 'advic help', 'advis', 'advisor', 'advisor lead', 'advisor lead account', 'advoc', 'advoc new', 'advoc new product', 'advoc research', 'advoc research divers', 'advocaci', 'advocaci support', 'advocaci support bid', 'adword', 'agenc', 'agencies', 'agenda', 'agreement', 'agreements', 'align', 'alloc', 'altern',

In [38]:
print(bow)

print(type(bow))
print(bow.shape)
print(len(vectorizer.get_feature_names()))

dtm = pd.DataFrame(bow, columns=vectorizer.get_feature_names())
new_data = pd.concat([data, dtm], axis=1)
print(new_data)
new_data.to_csv("dtm_jobs.csv", header= True)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
(1227, 1804)
1804
     Unnamed: 0 Company                                              Title  \
0             1  Google                       Google Cloud Program Manager   
1             2  Google  Supplier Development Engineer (SDE), Cable/Con...   
2             3  Google  Data Analyst, Product and Tools Operations, Go...   
3             4  Google            Developer Advocate, Partner Engineering   
4             5  Google     Program Manager, Audio Visual (AV) Deployments   
5             6  Google  Associate Account Strategist (Czech/Slovak), G...   
6             7  Google  Supplier Development Engineer, Camera, Consume...   
7             8  Google  Strategic Technology Partner Manager, Healthca...   
8             9  Google    Manufacturing Business Manager, Google Hardware   
9            10  Google  Solutions Architect, Healthcare a

In [32]:
corpus_null = data['Minimum.Qualifications']
corpus= corpus_null.fillna(" ") # clean 15 empty lines, replace null entries with space

#replacing punctuation
corpus = corpus.str.replace('\'',' ')
corpus = corpus.str.replace("-",' ')
corpus = corpus.str.replace(",",'')
corpus = corpus.str.replace("\\n",'. ')
corpus = corpus.str.replace('[^\w\s]','.')
corpus = corpus.str.replace("\..",'.')


#corpus = corpus.str.replace('.','')

st = PorterStemmer()
corpus = corpus.apply(lambda x: " ".join([st.stem(word) for word in x.split()]))#stem words

# tokenize all words 3 letters or longer.  Ignore 3-grams that occur in more than 727 or in less than 3 descriptions
vectorizer = CountVectorizer(stop_words = 'english', strip_accents=ascii, ngram_range=(3,3), analyzer = 'word',max_df=0.6, min_df=.005)
bow = np.array(vectorizer.fit_transform(corpus).toarray())
print("extracted " + str(len(vectorizer.get_feature_names())) + " features from " + str(len(corpus)) + " documents\n")
print(vectorizer.get_feature_names())

extracted 608 features from 1227 documents

['10 week month', '10 week program', '10 year experi', '10 year relev', '11 12 week', '11 week program', '12 week program', '12 year experi', '12 year relev', '2018 2019 2020', '2018 2019 pleas', '2018 abil speak', '2018 author work', '2018 decemb 2018', '2018 juli 2019', '2018 june 2019', '2019 2020 current', '2019 2020 design', '2019 abl complet', '2019 author work', '2019 avail intern', '2019 pleas includ', '2019 return educ', '2020 current enrol', '2020 design portfolio', '40 time requir', 'aas infrastructur servic', 'aas markets experi', 'aas platform servic', 'abil commit minimum', 'abil speak write', 'abil travel 40', 'abil travel 50', 'abl complet 11', 'abl complet minimum', 'abl speak write', 'account equival practic', 'administr ba program', 'advertis sale market', 'agenc corpor setting', 'agenc hous corpor', 'agil partner mid', 'aipei offic septemb', 'akarta offic septemb', 'anagement sale relationship', 'ani major univers', 'anthr

In [33]:
corpus_null = data['Preferred.Qualifications']
corpus= corpus_null.fillna(" ") # clean 15 empty lines, replace null entries with space

#replacing punctuation
corpus = corpus.str.replace('\'',' ')
corpus = corpus.str.replace("-",' ')
corpus = corpus.str.replace(",",'')
corpus = corpus.str.replace("\\n",'. ')
corpus = corpus.str.replace('[^\w\s]','.')
corpus = corpus.str.replace("\..",'.')


#corpus = corpus.str.replace('.','')

st = PorterStemmer()
corpus = corpus.apply(lambda x: " ".join([st.stem(word) for word in x.split()]))#stem words

# tokenize all words 3 letters or longer.  Ignore 3-grams that occur in more than 727 or in less than 3 descriptions
vectorizer = CountVectorizer(stop_words = 'english', strip_accents=ascii, ngram_range=(3,3), analyzer = 'word',max_df=0.6, min_df=.005)
bow = np.array(vectorizer.fit_transform(corpus).toarray())
print("extracted " + str(len(vectorizer.get_feature_names())) + " features from " + str(len(corpus)) + " documents\n")
print(vectorizer.get_feature_names())

extracted 1383 features from 1227 documents

['10 year experi', '10 year partner', '10 year relev', '2018 2019 2020', '2019 2020 demonstr', '2019 2020 relev', '2020 demonstr profici', '2020 relev work', 'aa iaas work', 'aas aas experi', 'aas aas technologies', 'aas experi work', 'aas infrastructur servic', 'aas technologies experi', 'abil adapt messag', 'abil analyz complex', 'abil appli brand', 'abil build influenti', 'abil build relationship', 'abil build strong', 'abil collabor build', 'abil comfort interact', 'abil commun complex', 'abil commun effect', 'abil craft compel', 'abil deal ambigu', 'abil deleg motiv', 'abil deliv high', 'abil drive implement', 'abil effect convers', 'abil effect influenc', 'abil effect oper', 'abil engag develop', 'abil engag senior', 'abil handl custom', 'abil handl highli', 'abil initi build', 'abil lead handl', 'abil lead manag', 'abil manag multipl', 'abil manag numer', 'abil meet exceed', 'abil multi task', 'abil navig ambigu', 'abil oper fast', 'a

In [28]:
corpus_null = data['Title']
corpus= corpus_null.fillna(" ") # clean 15 empty lines, replace null entries with space

#replacing punctuation
corpus = corpus.str.replace('\'',' ')
corpus = corpus.str.replace("-",' ')
corpus = corpus.str.replace(",",'')
corpus = corpus.str.replace("\\n",'. ')
corpus = corpus.str.replace('[^\w\s]','.')
corpus = corpus.str.replace("\..",'.')


#corpus = corpus.str.replace('.','')

st = PorterStemmer()
corpus = corpus.apply(lambda x: " ".join([st.stem(word) for word in x.split()]))#stem words

# tokenize all words 3 letters or longer.  Ignore 2-grams that occur in more than 727 or in less than 3 descriptions
vectorizer = CountVectorizer(stop_words = 'english', strip_accents=ascii, ngram_range=(2,2), analyzer = 'word',max_df=0.6, min_df=.0025)
bow = np.array(vectorizer.fit_transform(corpus).toarray())
print("extracted " + str(len(vectorizer.get_feature_names())) + " features from " + str(len(corpus)) + " documents\n")
print(vectorizer.get_feature_names())

extracted 273 features from 1227 documents

['2018 argentina', '2018 brazil', '2018 colombia', '2018 mexico', 'account execut', 'account lead', 'account manag', 'account strategist', 'ach integr', 'ad commerc', 'ad googl', 'administr busi', 'analyst consum', 'analyst data', 'analyst googl', 'analyst market', 'analyst product', 'analyst trust', 'analyt lead', 'analyt manag', 'android partner', 'architect googl', 'architect healthcar', 'art time', 'associ account', 'associ legal', 'attribut specialist', 'bilingual 2018', 'bold intern', 'brand studio', 'busi analyst', 'busi develop', 'busi intern', 'busi manag', 'busi partner', 'busi strategi', 'buy solut', 'chain manag', 'channel sale', 'channel specialist', 'cloud ach', 'cloud engin', 'cloud mea', 'cloud nglish', 'cloud platform', 'cloud profession', 'cloud support', 'cluster manag', 'commun googl', 'commun manag', 'commun program', 'consult ad', 'consult android', 'consult googl', 'consum hardwar', 'counsel commerci', 'custom develop',